name: Deploy to EC2

on:
  push:
    branches:
      - develop  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-13-61-11-77.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ubuntu@ec2-13-61-11-77.eu-north-1.compute.amazonaws.com << 'EOF'
            cd ~/loginapp || git clone https://github.com/venukumar9000/loginApp loginapp && cd loginapp
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
